name: Node.js CI

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: self-hosted

    env:
      DATABASE_URL: "postgresql://casaos:casaos@localhost:5432/"

    steps:
      - uses: actions/checkout@v4
      - run: npm ci --legacy-peer-deps
      - run: bun x prisma db push
      - run: bun x prisma db seed
      - run: bun x prisma generate
      - run: bun run build
      - run: |
          echo "DATABASE_URL=${{ env.DATABASE_URL }}" >> .env
          echo "NODE_ENV=Production" >> .env
      - run: pm2 restart am
